name: Replace placeholders in PR body
on: pull_request
jobs:
    build:
        name: Replace placeholders in PR body
        runs-on: ubuntu-latest
        steps:
        - name: replace step
          id: replace-step
          uses: robertmaier/pr-body-replace-action@v1
          with:
            pr-id: 2345